Fix Transform Not Calling All Transformations
svg-sprite/svg-sprite pull request #775
Opened 2023-02-09 01:09 UTC by babs20

Fixes #762 

This could also close #770

2023-02-15 08:37 UTC, Kreeg commented on lib/svg-sprite.js
> +            return cb => {
This name is shadowed by upper scope, pls change the name

2023-02-15 08:37 UTC, Kreeg commented on lib/svg-sprite.js
> +            return cb => {
Here is the same

2023-02-15 08:44 UTC, Kreeg requested changes
@babs20 hello! Thank you for contribution.

- Please fix minor issues here with naming
- Please squash all of your 3 commits into 1

2023-02-16 08:04 UTC, Kreeg commented
@babs20 hello! Please update commit message with more readable one, like `Fixed _transformShape not calling all transformations`

2023-02-16 14:53 UTC, babs20 commented
@Kreeg Okay, I think I fixed everything 🥳 . Thanks for the feedback on the git flow 😄

2023-02-20 08:10 UTC, merged

2023-02-20 08:10 UTC, Kreeg commented
@babs20 thanks for help!